### ISSUE TITLE
How can I customize the number of reviewer?

### ISSUE THREAD

**Issue by jlduu** [shellywhen/Journal-Response-Letter-Template-Latex#1]
How can I customize the number of reviewer?

**Comment by shellywhen** [comment]
> How can I customize the number of reviewer?

To add one reviewer, you may simply copy `R1.tex` to a new file, say `R5.tex` and include the new file in the main file (i.e., `review_response.tex`).

You may refer to Line 38~Line 41 [https://github.com/shellywhen/Journal-Response-Letter-Template-Latex/blob/main/review_response.tex](https://github.com/shellywhen/Journal-Response-Letter-Template-Latex/blob/main/review_response.tex) for file inclusion.

**Comment by shellywhen** [comment]
To add one reviewer, you may simply copy `R1.tex` to a new file, say `R5.tex` and include the new file in the main file (i.e., `review_response.tex`).

You may refer to Line 38~Line 41 [https://github.com/shellywhen/Journal-Response-Letter-Template-Latex/blob/main/review_response.tex](https://github.com/shellywhen/Journal-Response-Letter-Template-Latex/blob/main/review_response.tex) for file inclusion.
